Updating serverless to 3.0
newrelic/serverless-newrelic-lambda-layers pull request #203
Opened 2022-02-18 23:41 UTC by mrickard

Updating, addressing breaking changes, adding log dependencies, updating CircleCI image to Node 14 (preferred version for Serverless now).

<sup> Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>

2022-02-23 00:16 UTC, MattWhelan requested changes
How does this affect our existing users? Can they continue using 2.x?

2022-02-23 00:17 UTC, MattWhelan reviewed
Whoops. That was supposed to be a comment, not a change request.

2022-02-23 02:02 UTC, mrickard commented
@MattWhelan Current users could continue using 2.x with our 2.x version(s) of the plugin. Users who've updated to serverless 3.x would need to use this version of our plugin.

2022-02-23 19:17 UTC, mrickard commented
> @MattWhelan  What is the plan for bug fixes and feature releases on 2.x?

If there's a bug that needs to be fixed in 2.x, we could do that on a branch from before the merge, and make a release that targets that branch. I've not been aware of Serverless continuing development on superseded versions, though, so it's unlikely that we'd need to keep issuing updates. If we do, though, we can do a branch release. (After Serverless released 2.x, we updated the plugin and stopped updating our 1.x plugin.)

2022-02-23 19:55 UTC, MattWhelan submitted a review, later dismissed

2022-02-23 20:39 UTC, g-piffa commented
Thank you for working on this! As an outsider the only thing I'd suggest is to use the `peerDependencies` key ([see here](https://nodejs.org/es/blog/npm/peer-dependencies/)) in the `package.json` so it's clear what version this plugin depends on, providing a faster feedback loop.

2022-02-24 16:35 UTC, mrickard commented
> Thank you for working on this! As an outsider the only thing I'd suggest is to use the `peerDependencies` key ([see here](https://nodejs.org/es/blog/npm/peer-dependencies/)) in the `package.json` so it's clear what version this plugin depends on, providing a faster feedback loop.

Thank you for the note! We'll make a ticket to include that in a near-future release.

2022-02-24 16:57 UTC, mrickard commented
Fixing conflicts.

2022-02-24 22:21 UTC, yahmed153 approved these changes

2022-02-24 22:26 UTC, merged

2022-02-25 12:55 UTC, g-piffa commented
Great job @mrickard 🚀 🚀 🚀