Check for Serverless 3.x
newrelic/serverless-newrelic-lambda-layers pull request #221
Opened 2022-04-11 20:58 UTC by mrickard

Serverless 3.x introduced a breaking change for logging. Some customers are using the latest plugin with Serverless 2.x, so for that case, this PR would noop and print a warning. 

<sup> Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>

2022-04-12 22:06 UTC, MattWhelan requested changes

2022-04-12 22:06 UTC, MattWhelan commented on src/index.ts
> +        This plugin is optimized for Serverless 3.x. Please upgrade Serverless to >=3.0.0,
`optimized` isn't the same as `requires`. Let's be clear here.

Also, just checking: does `this.log.error` work with 2.x?

2022-04-13 12:58 UTC, kolanos approved these changes

2022-04-13 19:03 UTC, mrickard commented
@MattWhelan I've got a change that falls back to console if the new Serverless log interface isn't available. Having tested the new fallback with Serverless 2.x, the new version of this PR does now work in the old environment as well. (As a result, I've changed the messaging, noting that logging has changed, and directing which versions of the plugin or Serverless can be used if there are problems.)

2022-04-13 21:34 UTC, yahmed153 approved these changes

2022-04-13 21:48 UTC, MattWhelan approved these changes
Nice! This seems like a much more robust change.

2022-04-13 21:49 UTC, merged